name: Weekly Model Retrain

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC
  workflow_dispatch:    # Allows manual trigger via GitHub UI

jobs:
  retrain:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .     # Sets root directory in Python path to fix ModuleNotFoundError

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Model Training
      run: python src/models/train.py 

    - name: Sync Models to Google Drive
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} 
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }} # <-- Added this line
      run: python src/utils/gdrive_sync.py --upload
